/**
 * ObliWAN — bench account provisioning (M15).
 *
 * ┌─ THE ONLY PLACE IN THE PRODUCT ALLOWED TO WRITE `localUser` ─────────────┐
 * │ Everywhere else it is refused, and on purpose:                            │
 * │                                                                          │
 * │  - `planner.service` compiles a `localUser` delete or downgrade into a    │
 * │    `blocked / mgmt_path_veto` op instead of an instruction;               │
 * │  - `checkManagementIdentity` in K2 REJECTS a plan that would leave no     │
 * │    account able to log in from the concentrator;                          │
 * │  - and `healthGate` fails a wave whose post-change reconnect failed.      │
 * │                                                                          │
 * │ Those three exist because removing the last usable account leaves a       │
 * │ router that forwards packets perfectly and that nobody can enter — and on │
 * │ a brand with no on-device dead-man, that is a van.                        │
 * │                                                                          │
 * │ This file is the exception, and it is safe for exactly one reason: a box  │
 * │ on a workbench has an out-of-band path called "the console cable in the   │
 * │ preparer's hand". Nothing else about it is special.                       │
 * └──────────────────────────────────────────────────────────────────────────┘
 *
 * ┌─ THE SCOPE RULE, ENFORCED HERE RATHER THAN PROMISED ─────────────────────┐
 * │ One device, one session, no fan-out. There is no batch entry point in     │
 * │ this module and there must not be one: the danger was never a careless    │
 * │ operator, it was a correct operator running a correct action across four  │
 * │ hundred boxes. A tool that can only reach the router in front of it       │
 * │ cannot do that, whatever anyone types.                                    │
 * └──────────────────────────────────────────────────────────────────────────┘
 */

import type { DeviceFamily } from '@obliwan/shared';
import { SSH_DIALECTS } from '../services/change/sshDialects';

/** One account to create. The password is generated by the caller and goes to
 *  the vault through the normal path — never through the enrolment payload. */
export interface BenchAccount {
  username: string;
  password: string;
  /** `full` on every family we write today. A read-only service account cannot
   *  configure, and creating one here would be a net nobody asked for. */
  group: 'full';
}

export interface AccountDialect {
  /** Lines that CREATE the account. */
  create(account: BenchAccount): string[];
  /**
   * Lines that make it durable, if the CLI keeps a pending state. Mirrors
   * `SSH_DIALECTS[*].commitVerb` and exists for the same reason: on ZLD and
   * SonicOS a change that is never committed evaporates at the end of the
   * session, and a tool that reported success would have created nothing.
   */
  commit(): string[];
  /** Free note for whoever validates this against real hardware. */
  note: string;
}

/**
 * PROVENANCE, stated because it decides how much to trust this.
 *
 * RouterOS is the one dialect this repository can exercise: `fakeDeadmanRouter`
 * and `fakeRouterosServer` speak the real wire protocol, and `/user/add` is
 * covered by them. The other three come from vendor documentation and have
 * never been typed at an appliance — same standing as `SSH_DIALECTS`, and the
 * same instruction: capture a transcript at the first real session and correct
 * this table before it is used in anger.
 */
export const ACCOUNT_DIALECTS: Readonly<Partial<Record<DeviceFamily, AccountDialect>>> = {
  mikrotik_routeros7: {
    create: (a) => [`/user/add name=${a.username} password=${a.password} group=full`],
    commit: () => [],
    note: 'RouterOS applies immediately; there is no pending state to commit.',
  },
  mikrotik_routeros6: {
    create: (a) => [`/user add name=${a.username} password=${a.password} group=full`],
    commit: () => [],
    note: 'RouterOS 6 uses the space-separated form of the same menu.',
  },
  draytek_vigor: {
    create: (a) => [`sys admin ${a.username} ${a.password}`],
    commit: () => [],
    note: 'UNVERIFIED. Vigor applies per line and has no commit verb; the admin ' +
      'account syntax differs across trains and must be confirmed on hardware.',
  },
  zyxel_standalone: {
    create: (a) => [
      'configure terminal',
      `username ${a.username} password ${a.password} user-type admin`,
      'exit',
    ],
    commit: () => ['write'],
    note: 'UNVERIFIED. ZLD needs the explicit `write`: without it the account is ' +
      'lost at the next reboot, which looks exactly like drift.',
  },
  sonicwall_sonicos: {
    create: (a) => [
      'configure',
      `user local ${a.username}`,
      `password ${a.password}`,
      'group "SonicWALL Administrators"',
      'exit',
    ],
    commit: () => ['commit', 'exit'],
    note: 'UNVERIFIED. SonicOS is transactional: without `commit` the pending ' +
      'configuration is discarded when the session ends, and a tool that ' +
      'reported success would have created nothing.',
  },
};

export interface ProvisionPlan {
  family: DeviceFamily;
  /** Complete rendering. In memory only, never logged, never enrolled. */
  commands: string[];
  /** Same lines with the password replaced. This is what may be displayed. */
  redacted: string[];
  /** Whether the dialect has ever been confirmed on hardware. */
  verified: boolean;
  note: string;
}

/**
 * Render the account creation for one device.
 *
 * PURE — no socket, no session. So the refusals below are testable without a
 * router, and so the preparer can be shown exactly what will be sent before
 * anything is sent. A provisioning tool that will not show its own commands is
 * a tool nobody can review at the moment review is cheap.
 */
export function planProvisioning(
  family: DeviceFamily,
  accounts: readonly BenchAccount[],
): ProvisionPlan {
  const dialect = ACCOUNT_DIALECTS[family];
  if (!dialect) {
    throw new Error(
      `No account dialect for family '${family}'. Refusing rather than guessing: a wrong ` +
        'account command on a fresh router either does nothing or locks it, and both are ' +
        'discovered later.',
    );
  }
  if (accounts.length === 0) {
    throw new Error('No account requested. Enrolling a router with no way in is not a service.');
  }
  for (const a of accounts) {
    if (!/^[a-zA-Z0-9._-]{2,32}$/.test(a.username)) {
      throw new Error(
        `Refusing username "${a.username}": these CLIs are line-oriented and a space or a quote ` +
          'in a username is an injection into the next command, not a naming choice.',
      );
    }
    if (a.password.length < 12) {
      throw new Error('Refusing a password shorter than 12 characters on a fleet service account.');
    }
    if (/[\s"'`\\]/.test(a.password)) {
      throw new Error(
        'Refusing a password containing whitespace, quotes or a backslash: it would have to be ' +
          'escaped differently per dialect, and an escaping bug here writes the WRONG password ' +
          'and locks the box on its first real connection.',
      );
    }
  }

  const commands = [
    ...accounts.flatMap((a) => dialect.create(a)),
    ...dialect.commit(),
  ];
  const secrets = accounts.map((a) => a.password);
  const redacted = commands.map((line) =>
    secrets.reduce((acc, s) => acc.split(s).join('********'), line),
  );

  return {
    family,
    commands,
    redacted,
    verified: family.startsWith('mikrotik'),
    note: dialect.note,
  };
}

/**
 * A password nobody has to remember and nobody may choose.
 *
 * Generated locally, handed to the vault by the operator, and never sent in the
 * enrolment payload. The alphabet deliberately excludes whitespace, quotes and
 * backslashes — see the refusal above: an escaping difference between dialects
 * would write a password different from the one recorded, and the box would be
 * unreachable on its first real connection with nothing pointing at why.
 */
export function generateServicePassword(bytes = 24): string {
  const ALPHABET = 'ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789-_';
  // eslint-disable-next-line @typescript-eslint/no-var-requires
  const { randomBytes } = require('node:crypto') as typeof import('node:crypto');
  const buf = randomBytes(bytes);
  let out = '';
  for (const b of buf) out += ALPHABET[b % ALPHABET.length];
  return out;
}
